hl.on("hyprland.start", function () 
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("discord")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("flameshot")
    hl.exec_cmd("clipboard-sync")
    hl.exec_cmd("greenclip clear")
    hl.exec_cmd("greenclip daemon")
    hl.exec_cmd("firefox")
end)
